import csv
import os
import smtplib

from datetime import datetime , date , timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText 
from config import Config
from celery_app import celery
from extensions import db
from models import User ,StudentProfile ,CompanyProfile , PlacementDrive ,Application 

SMTP_HOST = 'localhost'
SMTP_PORT = 1025
SENDER_EMAIL = "placemetcell@ppa.com"
SENDER_PASSWORD = ""

def _send_email(to_address, subject, body ,content_type="text", attachments=None):
    msg = MIMEMultipart()
    msg['To'] = to_address
    msg['Subject'] = subject
    msg['From'] = "placemetcell@ppa.com"
    
    if content_type == "html":
        msg.attach(MIMEText(body, 'html'))
    else:
        msg.attach(MIMEText(body, 'plain'))
    s = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
    s.login(SENDER_EMAIL, SENDER_PASSWORD)
    s.send_message(msg)
    s.quit()
    return True 

#----------------------------------------------------------------------------------------------------------------
# Daily deadline remainders
#----------------------------------------------------------------------------------------------------------------
@celery.task(name = "task.send_daily_reminders")
def send_daily_reminder():
    today = date.today()
    horizon = today +timedelta(days=3)

    upcoming = (
        PlacementDrive.query.filter(
            PlacementDrive.status == "approved",
            PlacementDrive.application_deadline != None ,
            PlacementDrive.application_deadline >= today,
            PlacementDrive.application_deadline <=horizon
        ).all()
    )
    if not upcoming:
        return "No Upcoming daedlines in the next 3 days"
    students = StudentProfile.query.join(User).filter(
        User.is_active == True , User.is_blacklisted == False
    ).all()
    sent = 0
    for student in students:
        applied_drive_ids = {a.drive_id for a in student.applications}
        pending = [d for d in upcoming if d.id not in applied_drive_ids]
        if not pending:
            continue
        lines = "".join(
            f"<li><b>{d.job_title}</b> at {d.company.company_name}"
            f"(deadline :{d.application_deadline}) </li>"
            for d in pending
        )
        html = (
            f"<p>Hi {student.name},</p>"
            f"<p>These Placement drives close soon . Apply before the deadline:</P>"
            f"<ul>{lines}</ul>"
            f"<p> - Placement Cell</p>"
        )
        _send_email(student.user.email , "Upcoming Placement deadline" ,html)

#----------------------------------------------------------------------------------------------------------------
# Monthly activity report 
#----------------------------------------------------------------------------------------------------------------

def build_monthly_report_html(start , end):
    drives = PlacementDrive.query.filter(
        PlacementDrive.created_at >=start , PlacementDrive.created_at < end
    ).all()
    apps = Application.query.filter(
        Application.application_date >= start , Application.application_date < end
    ).all()
    selected = [a for a in apps if a.status == "selected"]

    rows = "".join(
        f"<tr><td>{d.job_title}</td><td>{d.company.company_name if d.company else '-'}</td>"
        f"<td>{d.status}</td><td>{len(d.applications)}</td></tr>"
        for d in drives
    )
    if not rows:
        rows = "<tr><td colspan='4' style='text-align:center'>No drives this month</td></tr>"
    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#222">
      <h2 style="color:#2c3e50">Monthly Placement Activity Report</h2>
      <p>Period: <b>{start.date()}</b> to <b>{(end - timedelta(days=1)).date()}</b></p>
      <div style="display:flex;gap:16px;margin:16px 0">
        <div style="padding:12px;border:1px solid #ddd;border-radius:8px">
          <h3 style="margin:0">{len(drives)}</h3><div>Drives conducted</div></div>
        <div style="padding:12px;border:1px solid #ddd;border-radius:8px">
          <h3 style="margin:0">{len(apps)}</h3><div>Applications received</div></div>
        <div style="padding:12px;border:1px solid #ddd;border-radius:8px">
          <h3 style="margin:0">{len(selected)}</h3><div>Students selected</div></div>
      </div>
      <table border="1" cellpadding="8" cellspacing="0"
             style="border-collapse:collapse;width:100%">
        <thead style="background:#2c3e50;color:#fff">
          <tr><th>Job Title</th><th>Company</th><th>Status</th><th>Applicants</th></tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="margin-top:16px;color:#777">Generated by Placement Portal Application.</p>
    </body></html>
    """
@celery.task(name="tasks.send_monthly_report")
def send_monthly_report():
    today = date.today()
    first_this_month = datetime(today.year , today.month , today.day)
    last_month_end = first_this_month
    prev = (first_this_month - timedelta(days=1))
    last_month_start = datetime(prev.year , prev.month ,1)

    html = build_monthly_report_html(last_month_start , last_month_end)
    admin = User.query.filter_by(role ="admin").first()
    _send_email(admin.email , "Monthly Placement Activity Report" , html)
    return "Monthly report sent to the Admin"
#----------------------------------------------------------------------------------------------------------------
# User triggered CSV export of a student's applications
#----------------------------------------------------------------------------------------------------------------
@celery.task(name="tasks.export_applications_csv" , bind = True)
def export_applications_csv(self , student_id):
    student = StudentProfile.query.get(student_id)
    if not student:
        return {"status":"error" , "message":"Student not found"}
    filename = f"applications_student_{student_id}_{int(datetime.utcnow().timestamp())}.csv"
    filepath = os.path.join(Config.Export , filename)

    with open(filepath , "w" , newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(
            ["Student ID", "Company Name", "Drive Title", "Application Status", "Application Date", "Interview Date"]
        )
        for app in student.applications:
            drive = app.drive
            writer.writerow([
                student.id,
                drive.company.company_name if drive and drive.company else "",
                drive.job_title if drive else "",
                app.status,
                app.application_date.strftime("%Y-%m-%d %H:%M") if app.application_date else "",
                app.interview_datetime.strftime("%Y-%m-%d %H:%M") if app.interview_datetime else "",
            ])

    _send_email(
        student.user.email,
        "Your application export is ready",
        f"<p>Hi {student.name}, </p><p>Your placement application history"
        f"has been exported to <b>{filename}</b> and is already to download"
        f"from your dashboard</p>"

    )
    return {"status":"done", "filename":filename}